version: '3.4'

services:
  authorization-mock-sample-api:
    container_name: authorization-mock-sample-api
    image: authorization-mock-sample-api
    build:
      context: .
      dockerfile: src/AuthorizationMockSample/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=5001
    ports:
      - "5001:5001"
  oidc-server:
    container_name: mockserver
    image: mockserver/mockserver:mockserver-5.15.0
    ports:
      - 5002:5002
    environment:
      - MOCKSERVER_PROPERTY_FILE=/config/mockserver.properties
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/mocked-requests.json
    volumes:
      - type: bind
        source: ./oidc-server
        target: /config
